### ISSUE TITLE
scannet data issue, last two dimisions are None

### ISSUE THREAD

**Issue by ForestWang** [embodied-generalist/embodied-generalist#24]
scannet_base/scan_data/pcd_with_global_alignment/**scene0738_00.pth**
(array([[0.44174623, 0.48032045, 0.11497073],
       [0.46305841, 0.48063248, 0.11281918],
       [0.26625684, 0.46335113, 0.13363716],
       ...,
       [7.51774406, 3.60136652, 0.81805444],
       [7.51661444, 3.60222292, 0.53582656],
       [7.51592398, 3.59875011, 0.62125003]]), array([[36., 28., 15.],
       [36., 28., 14.],
       [30., 17.,  6.],
       ...,
       [65., 50., 31.],
       [54., 45., 27.],
       [53., 45., 28.]], dtype=float32), **None, None**)
Traceback (most recent call last):
  File "/home/mi/robotics/embodied-generalist/check_dataset.py", line 44, in <module>
    main()
  File "/home/mi/robotics/embodied-generalist/check_dataset.py", line 39, in main
    scan = load_scannet(id)
  File "/home/mi/robotics/embodied-generalist/check_dataset.py", line 19, in load_scannet
    for i in range(instance_labels.max() + 1):
AttributeError: 'NoneType' object has no attribute 'max'

**Comment by huangjy-pku** [comment]
The data directory of ScanNet point cloud `pcd_with_global_alignment` covers all ScanNet scenes, including the test set, which has not been annotated. So, there are 100 scenes (test set) here whose instance annotation is `None`. In practice, our datasets only concern the training set and validation set of ScanNet scenes, so this issue does not matter.

**Comment by ForestWang** [comment]
thanks a lot.
