### ISSUE TITLE
An issue during the val_step

### ISSUE THREAD

**Issue by SitongGong** [embodied-generalist/embodied-generalist#29]
My program successfully completed the first epoch during training, but encountered an issue during the val_step.  I haven't found the specific reason yet and would like your help to take a look. Thank you!

My issue occurs at this line of code: output_txt = self.llm_tokenizer.batch_decode(outputs, skip_special_tokens=True)

This is the log：
Traceback (most recent call last):
  File "/root/anaconda3/envs/leo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/leo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/run.py", line 38, in <module>
    main()
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/run.py", line 34, in main
    trainer.run()
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/trainer/leo_trainer.py", line 377, in run
    is_best = self.val_step(2)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/trainer/leo_trainer.py", line 258, in val_step
    data_dict = self.forward(data_dict, inference=True)
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/trainer/leo_trainer.py", line 170, in forward
    return self.model.generate(data_dict)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/17709820071/embodied-generalist-main/embodied-generalist-main/model/leo_agent.py", line 430, in generate
    output_txt = self.llm_tokenizer.batch_decode(outputs, skip_special_tokens=True)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3446, in batch_decode
    return [
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3447, in <listcomp>
    self.decode(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3486, in decode
    return self._decode(
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 129, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by huangjy-pku** [comment]
Seems there are unexpected tokens for the tokenizer to decode. You can check the output tokens to be decoded (`outputs`).
