### ISSUE TITLE
Error :Can't load tokenizer for 'TBD'

### ISSUE THREAD

**Issue by BlackTea-c** [embodied-generalist/embodied-generalist#47]
Traceback (most recent call last):
  File "D:\embodied-generalist\inference.py", line 191, in main
    prober = LeoProber(cfg)
  File "D:\embodied-generalist\inference.py", line 41, in __init__
    self.model = LeoAgent(cfg)
  File "D:\embodied-generalist\model\leo_agent.py", line 24, in __init__
    self.llm_tokenizer = LlamaTokenizer.from_pretrained(
  File "D:\minicondaforme\envs\leo\lib\site-packages\transformers\tokenization_utils_base.py", line 1795, in from_pretrained
    raise EnvironmentError(
**OSError: Can't load tokenizer for 'TBD'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TBD' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.**

**And here is my default.yaml:**
defaults:
  - data: default
  - task: tuning_noact
  - llm: vicuna7b
  - vision2d: convnext
  - vision3d: ose3d_pointnetpp
  - _self_

# exp general info
name: LEO-1   # project name of wandb
note: default   # run name of wandb

rng_seed: 42
num_gpu: 4   # will be overrided by launch.py
mode: train
naming_keywords: [note]   # choose keywords to feature the exp run dir
base_dir: TBD
exp_dir: ""   # temporarily empty, will be set by run.py as base_dir + name + *naming_keywords
pretrained_ckpt_path: ""   # specified on launch

logger:
  name: wandb
  entity: TBD

dataset_wrapper_args:
  max_obj_len: 60

dataloader:
  train:
    batchsize: 4   # per-gpu batchsize
    num_workers: 4
  eval:
    batchsize: 4   # per-gpu batchsize
    num_workers: 4

trainer: LeoTrainer
training:
  epochs: ${task.training.epochs}
  gradient_accumulation_steps: 5
  grad_norm: 5.0
  optim:
    name: AdamW
    args:
      lr: ${task.training.lr}
      betas: [0.9, 0.999]
      weight_decay: 0.05
  schedule:
    name: linear_warmup_cosine_decay
    args:
      warmup_steps: 400

eval:
  num_batch_val: 50
  val_interval: 1

# model misc
clip_txt_guidance:
  flag: False   # for eai
  clip_out_dim: 1024

# inference
probe:
  sources: [3rscan]
  scene_ids: [0cac75d0-8d6f-2d13-8c26-d771a31c3f50]
  situations: ""
  instructions: [Describe this scene.]
  save_obj_tokens: True

**I just want to do inference.**

**Comment by BlackTea-c** [comment]
Alright,it seems like i forgot downloading vicuna7b

**Comment by BlackTea-c** [comment]
**Actually my Quesion is this：**
[2024-10-17 00:02:22,408][model.pcd_backbone][INFO] - Build PointcloudBackbone: PointNext
Error executing job with overrides: ['num_gpu=1', 'note=tuning_noact', "pretrained_ckpt_path='ckpoint/pytorch_model.bin'"]
Traceback (most recent call last):
  File "D:\embodied-generalist\inference.py", line 191, in main
    prober = LeoProber(cfg)
  File "D:\embodied-generalist\inference.py", line 41, in __init__
    self.model = LeoAgent(cfg)
  File "D:\embodied-generalist\model\leo_agent.py", line 51, in __init__
    self.pcd_encoder = build_module(cfg.vision3d)
  File "D:\embodied-generalist\model\build.py", line 6, in build_module
    return MODULE_REGISTRY.get(cfg.name)(cfg)
  File "D:\embodied-generalist\model\vision3d.py", line 55, in __init__
    self.obj_encoder = PointcloudBackbone(cfg.backbone)
  File "D:\embodied-generalist\model\pcd_backbone.py", line 28, in __init__
    self.pcd_net.load_state_dict(torch.load(path), strict=False)
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'D:\\embodied-generalist\\model\\pointnext'

**Comment by huangjy-pku** [comment]
Something wrong with loading the checkpoint of 3D encoder. It reports *permission denied*. You should make sure the checkpoint path is valid and can be accessed.

**Comment by BlackTea-c** [comment]
Oh thanks!I think i know how to do next
