### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'D:\\embodied-generalist\\model\\pointnetpp'

### ISSUE THREAD

**Issue by BlackTea-c** [embodied-generalist/embodied-generalist#48]
Help😖😖😖😖

[2024-10-17 00:37:11,176][model.pcd_backbone][INFO] - Build PointcloudBackbone: PointNetPP
Error executing job with overrides: ['num_gpu=1', 'note=tuning_noact', "pretrained_ckpt_path='ckpoint/pytorch_model.bin'"]
Traceback (most recent call last):
  File "D:\embodied-generalist\inference.py", line 191, in main
    prober = LeoProber(cfg)
  File "D:\embodied-generalist\inference.py", line 41, in __init__
    self.model = LeoAgent(cfg)
  File "D:\embodied-generalist\model\leo_agent.py", line 51, in __init__
    self.pcd_encoder = build_module(cfg.vision3d)
  File "D:\embodied-generalist\model\build.py", line 6, in build_module
    return MODULE_REGISTRY.get(cfg.name)(cfg)
  File "D:\embodied-generalist\model\vision3d.py", line 55, in __init__
    self.obj_encoder = PointcloudBackbone(cfg.backbone)
  File "D:\embodied-generalist\model\pcd_backbone.py", line 28, in __init__
    self.pcd_net.load_state_dict(torch.load(path), strict=False)
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\minicondaforme\envs\leo\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'D:\\embodied-generalist\\model\\pointnetpp'

**Comment by huangjy-pku** [comment]
Please follow the [readme](https://github.com/embodied-generalist/embodied-generalist?tab=readme-ov-file#model-weights) to prepare files.

**Comment by BlackTea-c** [comment]
solved,thanks
